# OneTrainer UI 中文翻译映射
# 由 Hermes Agent 生成

TRANSLATIONS = {
    # === 顶部栏 ===
    "Load Preset": "加载预设",
    "Load config": "加载配置",
    "Save config": "保存配置",
    "Wiki": "Wiki",
    "OneTrainer": "OneTrainer",

    # === 训练标签页 ===
    "Concept": "数据集",
    "Training": "训练",
    "Sampling": "采样",
    "Backup": "备份",
    "Cloud": "云端",
    "Model": "模型",
    "Additional Embeddings": "附加嵌入",

    # === 概念/数据集 ===
    "Add Concept": "添加数据集",
    "Add Config": "添加配置",
    "Add Sample": "添加采样",
    "Name": "名称",
    "Path": "路径",
    "Enabled": "启用",
    "Concept Type": "数据集类型",
    "Prompt Source": "提示词来源",
    "Include Subdirectories": "包含子目录",
    "Resolution Override": "分辨率覆盖",
    "Image Variations": "图像变体",
    "Text Variations": "文本变体",
    "Crop Jitter": "裁剪抖动",
    "Crop Variation": "裁剪变化",
    "Balancing": "平衡策略",
    "Loss Weight": "损失权重",
    "Tag Shuffling": "标签打乱",
    "Tag Dropout": "标签丢弃",
    "Keep Tag Count": "保留标签数",
    "Tag Delimiter": "标签分隔符",
    "Special Tags Regex": "特殊标签正则",
    "Special Dropout Tags": "特殊丢弃标签",
    "Dropout Mode": "丢弃模式",
    "Captialization Mode": "大小写模式",
    "Randomize Capitalization": "随机大小写",
    "Force Lowercase": "强制小写",
    "Probability": "概率",
    "Random": "随机",
    "Random Weighted": "随机加权",
    "Fixed": "固定",
    "Full": "全部",
    "None": "无",
    "Random Flip": "随机翻转",
    "Random Rotation": "随机旋转",
    "Random Brightness": "随机亮度",
    "Random Contrast": "随机对比度",
    "Random Hue": "随机色相",
    "Random Saturation": "随机饱和度",
    "Random Rotate and Crop": "随机旋转裁剪",
    "Circular Mask Generation": "圆形遮罩生成",
    "Masked Training": "遮罩训练",
    "Blacklist": "黑名单",
    "Whitelist": "白名单",
    "Enable or disable this concept": "启用或禁用此数据集",
    "Name of the concept": "数据集名称",
    "Path where the training data is located": "训练数据所在路径",
    "Enables random cropping of samples": "启用样本随机裁剪",
    "Enables tag shuffling": "启用标签打乱",
    "The delimiter between tags": "标签之间的分隔符",
    "The loss multiplyer for this concept.": "此数据集的损失乘数",
    "From image file name": "从图像文件名",
    "From single text file": "从单个文本文件",
    "From text file per sample": "从每样本文本文件",
    "Includes images from subdirectories into the dataset": "将子目录中的图像包含到数据集中",
    "Enable this augmentation with fixed values": "以固定值启用此增强",
    "Enable this augmentation with random values": "以随机值启用此增强",
    "Randomly flip the sample during training": "训练时随机翻转样本",
    "Randomly rotates the sample during training": "训练时随机旋转样本",
    "Randomly adjusts the brightness of the sample during training": "训练时随机调整样本亮度",
    "Randomly adjusts the contrast of the sample during training": "训练时随机调整样本对比度",
    "Randomly adjusts the hue of the sample during training": "训练时随机调整样本色相",
    "Randomly adjusts the saturation of the sample during training": "训练时随机调整样本饱和度",
    "Enables random dropout for tags in the captions.": "启用标签随机丢弃",
    "Probability to drop tags, from 0 to 1.": "标签丢弃概率，0到1",
    "Automatically create circular masks for masked training": "自动为遮罩训练创建圆形遮罩",
    "Enables randomization of capitalization for tags in the caption.": "启用标签大小写随机化",
    "If enabled, converts the caption to lowercase before any further processing.": "启用后，将标签转为小写后再处理",
    "Refresh Basic": "刷新基本",
    "Refresh Advanced": "刷新高级",
    "Reload basic statistics for the concept directory": "重新加载数据集目录的基本统计",
    "Reload advanced statistics for the concept directory": "重新加载数据集目录的高级统计",
    "Abort Scan": "中止扫描",
    "Stop the currently running scan if it's taking a long time - advanced scan will be slow on large folders and on HDDs": "如果扫描时间过长则中止——高级扫描对大文件夹和HDD较慢",
    "Directories": "目录数",
    "Total Size": "总大小",
    "Token count": "Token数",
    "Frames": "帧数",
    "Time taken to process concept directory": "处理数据集目录耗时",
    "Total number of image files with an associated caption": "有关联标签的图像文件总数",
    "Total number of image files with an associated mask": "有关联遮罩的图像文件总数",
    "Total size of all image, mask, and caption files in MB": "图像、遮罩和标签文件总大小(MB)",
    "Average fps of videos in the concept": "数据集中视频平均帧率",
    "Video in concept with highest fps": "数据集中最高帧率视频",
    "Video in concept with the lowest fps": "数据集中最低帧率视频",
    "Longest video in the concept by number of frames": "数据集中帧数最多的视频",
    "Shortest video in the concept by number of frames": "数据集中帧数最少的视频",

    # === 训练参数 ===
    "Learning Rate": "学习率",
    "The base learning rate": "基础学习率",
    "Learning Rate Scheduler": "学习率调度器",
    "Learning rate scheduler that automatically changes the learning rate during training": "训练过程中自动调整学习率的调度器",
    "Learning Rate Warmup Steps": "学习率预热步数",
    "Learning Rate Cycles": "学习率周期数",
    "Learning Rate Min Factor": "学习率最小因子",
    "Learning Rate Scaler": "学习率缩放器",
    "Local Batch Size": "本地批次大小",
    "The batch size of one training step. If you use multiple GPUs, this is the batch size of each GPU (local batch size).": "单步训练的批次大小。多GPU时每块GPU的批次大小",
    "Accumulation Steps": "梯度累积步数",
    "Number of accumulation steps. Increase this number to trade batch size for training speed": "梯度累积步数，增加此值以训练速度换取更大批次",
    "Epochs": "训练轮数",
    "The number of epochs for a full training run": "完整训练运行的轮数",
    "Optimizer": "优化器",
    "The type of optimizer": "优化器类型",
    "Optimizer Settings": "优化器设置",
    "Optimizer Defaults": "优化器默认值",
    "Load Defaults": "加载默认值",
    "Load default settings for the selected optimizer": "加载所选优化器的默认设置",
    "Gradient Checkpointing": "梯度检查点",
    "Enables gradient checkpointing for this component. Reduces VRAM usage at the cost of training speed": "启用梯度检查点，减少显存占用但降低训练速度",
    "Clip Grad Norm": "梯度裁剪",
    "Clips the gradient norm. Leave empty to disable gradient clipping.": "梯度范数裁剪，留空则禁用",
    "Clip Skip": "Clip跳层",
    "The number of additional clip layers to skip. 0 = the model default": "额外跳过的Clip层数，0为模型默认",
    "Caption Dropout Probability": "标签丢弃概率",
    "The Probability for dropping the text encoder conditioning": "丢弃文本编码器条件的概率",
    "Resolution": "分辨率",
    "The resolution used for training. Optionally specify multiple resolutions separated by a comma, or a single exact resolution in the format <width>x<height>": "训练分辨率，可用逗号分隔多个分辨率，或指定 <宽>x<高> 格式",
    "Attention": "注意力机制",
    "The attention mechanism used during training. Use `torch SDPA` on linux. On windows, `flash-attn` can be faster, but it has to be installed manually and does not support all models. `torch cuDNN` is an alternative backend some models require or benefit from.": "训练使用的注意力机制。Linux用torch SDPA，Windows可手动安装flash-attn",
    "Train UNet": "训练UNet",
    "Enables training the UNet model": "启用UNet模型训练",
    "Train Text Encoder": "训练文本编码器",
    "Enables training the text encoder model": "启用文本编码器训练",
    "Train Transformer": "训练Transformer",
    "Enables training the Transformer model": "启用Transformer模型训练",
    "Train Prior": "训练Prior",
    "Enables training the Prior model": "启用Prior模型训练",
    "UNet Learning Rate": "UNet学习率",
    "The learning rate of the UNet. Overrides the base learning rate": "UNet学习率，覆盖基础学习率",
    "Text Encoder Learning Rate": "文本编码器学习率",
    "The learning rate of the text encoder. Overrides the base learning rate": "文本编码器学习率，覆盖基础学习率",
    "Transformer Learning Rate": "Transformer学习率",
    "The learning rate of the Transformer. Overrides the base learning rate": "Transformer学习率，覆盖基础学习率",
    "Prior Learning Rate": "Prior学习率",
    "The learning rate of the Prior. Overrides the base learning rate": "Prior学习率，覆盖基础学习率",
    "Embeddings Learning Rate": "嵌入学习率",
    "The learning rate of embeddings. Overrides the base learning rate": "嵌入学习率，覆盖基础学习率",
    "Text Encoder Sequence Length": "文本编码器序列长度",
    "Text Encoder": "文本编码器",
    "The text encoder weight data type": "文本编码器权重数据类型",
    "Text Encoder Data Type": "文本编码器数据类型",
    "UNet Data Type": "UNet数据类型",
    "The unet weight data type": "UNet权重数据类型",
    "Transformer Data Type": "Transformer数据类型",
    "The transformer weight data type": "Transformer权重数据类型",
    "Prior Data Type": "Prior数据类型",
    "The prior weight data type": "Prior权重数据类型",
    "VAE Data Type": "VAE数据类型",
    "The vae weight data type": "VAE权重数据类型",
    "VAE Override": "VAE覆盖",
    "Train Data Type": "训练数据类型",
    "The mixed precision data type used for training. This can increase training speed, but reduces precision": "训练混合精度数据类型，可提高速度但降低精度",
    "Fallback Train Data Type": "回退训练数据类型",
    "The mixed precision data type used for training stages that don't support float16 data types. This can increase training speed, but reduces precision": "不支持float16的训练阶段的混合精度数据类型",
    "Output Data Type": "输出数据类型",
    "EMA": "EMA",
    "EMA Decay": "EMA衰减",
    "Decay parameter of the EMA model. Higher numbers will average more steps. For datasets of hundreds or thousands of images, set this to 0.9999. For smaller datasets, set it to 0.999 or even 0.998": "EMA模型衰减参数。大数据集设0.9999，小数据集设0.999或0.998",
    "EMA Update Step Interval": "EMA更新步间隔",
    "Number of steps between EMA update steps": "EMA更新之间的步数",
    "EMA averages the training progress over many steps, better preserving different concepts in big datasets": "EMA对多步训练取平均，更好地保留大数据集中的不同概念",
    "Offset Noise Weight": "偏移噪声权重",
    "The weight of offset noise added to each training step": "每步训练添加的偏移噪声权重",
    "Perturbation Noise Weight": "扰动噪声权重",
    "The weight of perturbation noise added to each training step": "每步训练添加的扰动噪声权重",
    "Generalized Offset Noise": "广义偏移噪声",
    "Per-timestep 'brightness knob' instead of a fixed offset - steadier training, better starts, and improved very dark/bright images. Compatible with V-pred and Eps-pred. Start with 0.02 and adjust as needed.": "逐时间步的亮度调节，训练更稳定。建议从0.02开始",
    "Guidance Scale": "引导尺度",
    "The guidance scale of guidance distilled models passed to the transformer during training.": "引导蒸馏模型传递给Transformer的引导尺度",
    "Masked Prior Preservation Weight": "遮罩Prior保留权重",
    "Preserves regions outside the mask using the original untrained model output as a target. Only available for LoRA training. If enabled, use a low unmasked weight.": "使用原始未训练模型输出保留遮罩外区域，仅限LoRA训练",
    "Normalize Masked Area Loss": "归一化遮罩区域损失",
    "When masked training is enabled, normalizes the loss for each sample based on the sizes of the masked region": "遮罩训练时按遮罩区域大小归一化损失",
    "Unmasked Probability": "未遮罩概率",
    "When masked training is enabled, specifies the number of training steps done on unmasked samples": "遮罩训练时未遮罩样本的训练步数",
    "Unmasked Weight": "未遮罩权重",
    "When masked training is enabled, specifies the loss weight of areas outside the masked region": "遮罩训练时遮罩外区域的损失权重",
    "Force Attention Mask": "强制注意力遮罩",
    "Force enables passing of a text embedding attention mask to the transformer. This can improve training on shorter captions.": "强制向Transformer传递文本嵌入注意力遮罩，可改善短标签训练",
    "Force Circular Padding": "强制循环填充",
    "Enables circular padding for all conv layers to better train seamless images": "为所有卷积层启用循环填充，更好地训练无缝图像",
    "Autocast Cache": "自动转换缓存",
    "Enables the autocast cache. Disabling this reduces memory usage, but increases training time": "启用自动转换缓存，禁用可减少内存但增加训练时间",
    "Offload Activations": "卸载激活值",
    "Offloads this component's activations to CPU during training to reduce VRAM usage": "训练时将激活值卸载到CPU以减少显存占用",
    "Layer Offload Fraction": "层卸载比例",
    "Fraction of this component's layers to offload to CPU to reduce VRAM usage. Increases training time and RAM usage. 0=disabled, 1=all layers": "卸载到CPU的层比例，0=禁用，1=全部",
    "Latent Caching": "潜在缓存",
    "Caching of intermediate training data that can be re-used between epochs": "缓存可在轮次间复用的中间训练数据",
    "Clear cache before training": "训练前清除缓存",
    "Clears the cache directory before starting to train. Only disable this if you want to continue using the same cached data. Disabling this can lead to errors, if other settings are changed during a restart": "训练前清除缓存目录，仅在使用相同缓存数据时禁用",
    "Timestep Distribution": "时间步分布",
    "Selects the function to sample timesteps during training": "选择训练时的时间步采样函数",
    "Timestep Shift": "时间步偏移",
    "Shift the timestep distribution. Use the preview to see more details.": "偏移时间步分布，使用预览查看详情",
    "Dynamic Timestep Shifting": "动态时间步偏移",
    "Dynamically shift the timestep distribution based on resolution. If enabled, the shifting parameters are taken from the model's scheduler configuration and Timestep Shift is ignored.": "根据分辨率动态偏移时间步分布，启用后忽略固定偏移",
    "Noising Bias": "噪声偏差",
    "Controls the bias parameter of the timestep distribution function. Use the preview to see more details.": "控制时间步分布函数的偏差参数",
    "Noising Weight": "噪声权重",
    "Controls the weight parameter of the timestep distribution function. Use the preview to see more details.": "控制时间步分布函数的权重参数",
    "Min Noising Strength": "最小噪声强度",
    "Specifies the minimum noising strength used during training. This can help to improve composition, but prevents finer details from being trained": "训练最小噪声强度，有助于构图但会阻碍细节训练",
    "Max Noising Strength": "最大噪声强度",
    "Specifies the maximum noising strength used during training. This can be useful to reduce overfitting, but also reduces the impact of training samples on the overall image composition": "训练最大噪声强度，可减少过拟合但降低样本对构图的影响",
    "Loss Scaler": "损失缩放器",
    "Selects the type of loss scaling to use during training. Functionally equated as: Loss * selection": "训练损失缩放类型，等效于: Loss * 选择值",
    "Loss Weight Function": "损失权重函数",
    "Choice of loss weight function. Can help the model learn details more accurately.": "损失权重函数选择，帮助模型更准确学习细节",
    "Huber Delta": "Huber Delta",
    "Delta parameter for huber loss": "Huber损失的delta参数",
    "Huber Strength": "Huber强度",
    "Huber loss strength for custom loss settings. Less sensitive to outliers than MSE. Strengths should generally sum to 1.": "Huber损失强度，比MSE对异常值更不敏感",
    "MSE Strength": "MSE强度",
    "Mean Squared Error strength for custom loss settings. Strengths should generally sum to 1.": "均方误差强度，强度总和应为1",
    "MAE Strength": "MAE强度",
    "Mean Absolute Error strength for custom loss settings. Strengths should generally sum to 1.": "平均绝对误差强度，强度总和应为1",
    "VB Strength": "VB强度",
    "Variational lower-bound strength for custom loss settings. Should be set to 1 for variational diffusion models": "变分下界强度，变分扩散模型应设为1",
    "Gamma": "Gamma",
    "Inverse strength of loss weighting. Range: 1-20, only applies to Min SNR and P2.": "损失权重逆强度，范围1-20，仅用于Min SNR和P2",
    "Rescale Noise Scheduler + V-pred": "重缩放噪声调度+V预测",
    "Rescales the noise scheduler to a zero terminal signal to noise ratio and switches the model to a v-prediction target": "将噪声调度器重缩放至零终端信噪比，切换模型到v预测目标",
    "Custom Conditioning Image": "自定义条件图像",
    "When custom conditioning image is enabled, will use png postfix with -condlabel instead of automatically generated.It's suitable for special scenarios, such as object removal, allowing the model to learn a certain behavior concept": "启用自定义条件图像，适用于对象移除等特殊场景",
    "Dropout Probability": "丢弃概率",
    "Dropout probability. This percentage of model nodes will be randomly ignored at each training step. Helps with overfitting. 0 disables, 1 maximum.": "丢弃概率，每步随机忽略此比例的模型节点，0=禁用",
    "Dataloader Threads": "数据加载线程",
    "Number of threads used for the data loader. Increase if your GPU has room during caching, decrease if it's going out of memory during caching.": "数据加载线程数，缓存时GPU有余量可增加",
    "Layer Filter": "层过滤器",
    "Comma-separated list of diffusion layers to train. Regular expressions (if toggled) are supported. Any model layer with a matching name will be trained": "逗号分隔的训练层列表，支持正则表达式",
    "Preserve Embedding Norm": "保留嵌入范数",
    "Rescales each trained embedding to the median embedding norm": "将每个训练嵌入重缩放至中位嵌入范数",
    "Compile transformer blocks": "编译Transformer块",
    "Uses torch.compile and Triton to significantly speed up training. Only applies to transformer/unet. Disable in case of compatibility issues.": "使用torch.compile和Triton加速训练，如有兼容问题请禁用",
    "Stop Training After": "训练停止条件",
    "Validate after": "验证间隔",
    "The interval used when validate training": "训练验证间隔",
    "Validation": "验证",
    "Enable validation steps and add new graph in tensorboard": "启用验证步骤并在Tensorboard添加图表",
    "Include Text Encoder {i}": "包含文本编码器{i}",
    "Includes text encoder {i} in the training run": "在训练中包含文本编码器{i}",
    "Text Encoder {i} Learning Rate": "文本编码器{i}学习率",
    "Text Encoder {i} Clip Skip": "文本编码器{i} Clip跳层",
    "Text Encoder {i} Sequence Length": "文本编码器{i}序列长度",
    "Train Text Encoder {i}": "训练文本编码器{i}",
    "Train Text Encoder {i} Embedding": "训练文本编码器{i}嵌入",
    "Enables training the text encoder {i} model": "启用文本编码器{i}训练",
    "Enables training embeddings for the text encoder {i} model": "启用文本编码器{i}嵌入训练",
    "The learning rate of the text encoder {i}. Overrides the base learning rate": "文本编码器{i}学习率，覆盖基础学习率",
    "The Probability for dropping the text encoder {i} conditioning": "丢弃文本编码器{i}条件的概率",
    "When to stop training the text encoder {i}": "何时停止训练文本编码器{i}",
    "When to stop training the UNet": "何时停止训练UNet",
    "When to stop training the text encoder": "何时停止训练文本编码器",
    "When to stop training the Transformer": "何时停止训练Transformer",
    "When to stop training the Prior": "何时停止训练Prior",
    "When to stop training the embedding": "何时停止训练嵌入",
    "Include Unconditional Transformer": "包含无条件Transformer",
    "Loads the dedicated unconditional transformer used for the negative branch of CFG": "加载用于CFG负分支的专用无条件Transformer",
    "Unconditional Transformer Data Type": "无条件Transformer数据类型",
    "The weight data type of the unconditional transformer, used for the negative branch of CFG during sampling": "无条件Transformer权重数据类型，用于CFG负分支",
    "Include Config": "包含配置",
    "Include the training configuration in the final model. Only supported for safetensors files.": "将训练配置包含在最终模型中，仅支持safetensors",
    "Prevent Overwrites": "防止覆盖",
    "When enabled, output paths that already exist on disk will be flagged as invalid to avoid accidental overwrites": "启用后，已存在的输出路径将被标记为无效以防止意外覆盖",
    "Only Cache": "仅缓存",
    "Only populate the cache, without any training": "仅填充缓存，不进行训练",
    "Offline Mode": "离线模式",
    "Skip the Hugging Face login and resolve every model from the local cache only.": "跳过Hugging Face登录，仅从本地缓存加载模型",
    "Async Offloading": "异步卸载",
    "Overlaps CPU<->GPU transfers with computation using CUDA streams. Applies to every offloaded component": "使用CUDA流重叠CPU<->GPU传输与计算",
    "Async Gradient Reduce": "异步梯度归约",
    "Multi-GPU: Asynchroniously start the gradient reduce operations during the backward pass. Can be more efficient, but requires some VRAM.": "多GPU：反向传播时异步启动梯度归约，更高效但占用显存",
    "Fused Gradient Reduce": "融合梯度归约",
    "Multi-GPU: Gradient synchronisation during the backward pass. Can be more efficient, especially with Async Gradient Reduce": "多GPU：反向传播时的梯度同步，配合异步梯度归约更高效",
    "Gradient Reduce Precision": "梯度归约精度",
    "Device Indexes": "设备索引",
    "Enable multi-GPU training": "启用多GPU训练",

    # === 模型标签页 ===
    "Base Model": "基础模型",
    "Base Model Name": "基础模型名称",
    "Filename, directory or Hugging Face repository of the base model": "基础模型文件名、目录或Hugging Face仓库",
    "Output": "输出",
    "Model Output Destination": "模型输出目标",
    "Filename or directory where the output model is saved": "输出模型保存的文件名或目录",
    "Output Format": "输出格式",
    "Format to use when saving the output model": "保存输出模型的格式",
    "Save Filename Prefix": "保存文件名前缀",
    "The prefix for filenames used when saving the model during training": "训练时保存模型的文件名前缀",
    "Workspace Directory": "工作空间目录",
    "The directory where all files of this training run are saved": "此训练运行所有文件保存的目录",
    "Cache Directory": "缓存目录",
    "The directory where cached data is saved": "缓存数据保存的目录",
    "Debug Directory": "调试目录",
    "The directory where debug data is saved": "调试数据保存的目录",
    "Hugging Face Cache Directory": "Hugging Face缓存目录",
    "Huggingface cache Directory": "Hugging Face缓存目录",
    "Directory used to cache Hugging Face model downloads.": "Hugging Face模型下载缓存目录",
    "Hugging Face Token": "Hugging Face令牌",
    "Enter your Hugging Face access token if you have used a protected Hugging Face repository below.\nThis value is stored separately, not saved to your configuration file.": "如果使用了受保护的Hugging Face仓库，请输入访问令牌。此值单独存储，不保存到配置文件",
    "Save Every": "保存间隔",
    "The interval used when automatically saving the model during training": "训练时自动保存模型的间隔",
    "Sample After": "采样间隔",
    "The interval used when automatically sampling from the model during training": "训练时自动采样的间隔",
    "Backup After": "备份间隔",
    "The interval used when automatically creating model backups during training": "训练时自动创建模型备份的间隔",
    "Backup Before Save": "保存前备份",
    "Create a full backup before saving the final model": "保存最终模型前创建完整备份",
    "Rolling Backup": "滚动备份",
    "If rolling backups are enabled, older backups are deleted automatically": "启用滚动备份后自动删除旧备份",
    "Rolling Backup Count": "滚动备份数量",
    "Defines the number of backups to keep if rolling backups are enabled": "滚动备份保留的数量",
    "Continue from last backup": "从上次备份继续",
    "Automatically continues training from the last backup saved in <workspace>/backup": "自动从<workspace>/backup中的上次备份继续训练",
    "Output embedding": "输出嵌入",
    "Output embeddings are calculated at the output of the text encoder, not the input. This can improve results for larger text encoders and lower VRAM usage.": "在文本编码器输出处计算嵌入，可改善大文本编码器效果并降低显存",
    "Quantization": "量化",
    "Quantization Layer Filter": "量化层过滤器",
    "Comma-separated list of layers to quantize. Regular expressions (if toggled) are supported. Any model layer with a matching name will be quantized": "逗号分隔的量化层列表，支持正则表达式",
    "Select a preset defining which layers to quantize. Quantization of certain layers can decrease model quality. Only applies to the transformer/unet": "选择量化层预设，量化某些层可能降低模型质量",
    "SVDQuant": "SVDQuant",
    "SVDQuant Rank": "SVDQuant秩",
    "Rank for SVDQuant weights decomposition": "SVDQuant权重分解的秩",
    "What datatype to use for SVDQuant weights decomposition.": "SVDQuant权重分解的数据类型",
    "Embedding": "嵌入",
    "Base embedding": "基础嵌入",
    "The base embedding to train on. Leave empty to create a new embedding": "训练的基础嵌入，留空创建新嵌入",
    "Initial embedding text": "初始嵌入文本",
    "The initial embedding text used when creating a new embedding": "创建新嵌入时的初始文本",
    "Placeholder": "占位符",
    "The placeholder used when using the embedding in a prompt": "在提示词中使用嵌入的占位符",
    "Bundle Embeddings": "捆绑嵌入",
    "Number of tokens for captions": "标签Token数",
    "The token count used when creating a new embedding. Leave empty to auto detect from the initial embedding text.": "新嵌入的Token数，留空自动检测",
    "Alpha": "Alpha",
    "Applies a scaling factor to the learned weights. This ensures that the effective learning rate remains consistent across different block sizes. Without this, different block sizes require significantly different learning rates.": "学习权重缩放因子，确保不同块大小下有效学习率一致",
    "Apply DoRA on Output Axis": "在输出轴应用DoRA",
    "Apply on output axis (DoRA Only)": "在输出轴应用（仅DoRA）",
    "Apply the DoRA weight decomposition on the output axis instead of the input axis.": "在输出轴而非输入轴应用DoRA权重分解",
    "Decompose Both Matrices": "分解两个矩阵",
    "Perform rank decomposition on both Kronecker product matrices (W1 and W2). Only effective for very small dimensions.": "对两个Kronecker积矩阵进行秩分解，仅对极小维度有效",
    "Decomposition Factor": "分解因子",
    "Factor for Kronecker product decomposition. -1 for auto, which is recommended. Changing this drastically affects parameter count.": "Kronecker积分解因子，-1为自动（推荐）",
    "Block Share": "块共享",
    "Share the OFT parameters between blocks. A single rotation matrix is shared across all blocks within a layer, drastically cutting the number of trainable parameters and yielding very compact adapter files, potentially improving generalization but at the cost of significant expressiveness, which can lead to underfitting on more complex or diverse tasks.": "块间共享OFT参数，大幅减少可训练参数，但可能降低表达能力",
    "Decompose LoRA Weights (aka, DoRA).": "分解LoRA权重（即DoRA）",
    "Apply weight decomposition (DoRA) on top of the LoKr update.": "在LoKr更新上应用权重分解（DoRA）",
    "Apply the weight decomposition on the output axis instead of the input axis.": "在输出轴而非输入轴应用权重分解",
    "Add an epsilon to the norm divison calculation in DoRA. Can aid in training stability, and also acts as regularization.": "在DoRA范数除法中添加epsilon，有助于训练稳定性",
    "The dimension parameter used for the secondary decomposition. Analogous to rank in LoRA.": "二次分解的维度参数，类似于LoRA的秩",
    "Forces the second Kronecker matrix (W2) to be a full matrix, ignoring the dimension setting. For expert use.": "强制第二个Kronecker矩阵为全矩阵，忽略维度设置",
    "Use Tucker decomposition for convolutional layers. Can be more efficient for some architectures.": "对卷积层使用Tucker分解，某些架构更高效",
    "Uses an accelerated path that bypasses the materialization of the full Kronecker product. This delivers a massive speedup to the LoKr without sacrificing precision. Highly recommended.": "使用加速路径绕过完整Kronecker积的实现，大幅加速LoKr",
    "Only implemented for LoRA.": "仅对LoRA实现",

    # === 采样 ===
    "Sample": "采样",
    "Prompt": "提示词",
    "Negative Prompt": "负面提示词",
    "Width": "宽度",
    "Height": "高度",
    "Seed": "种子",
    "Steps": "步数",
    "CFG Scale": "CFG尺度",
    "Sampler": "采样器",
    "Update Preview": "更新预览",
    "Preview image": "预览图",
    "The base image used when inpainting.": "修复使用的基础图像",
    "The mask used when inpainting.": "修复使用的遮罩",
    "Enables inpainting sampling. Only available when sampling from an inpainting model.": "启用修复采样，仅修复模型可用",
    "Number of frames to generate. Only used when generating videos.": "生成帧数，仅视频生成时使用",
    "Length in seconds of audio output.": "音频输出长度（秒）",
    "Whether to include non-ema sampling when using ema.": "使用EMA时是否包含非EMA采样",
    "Samples to Tensorboard": "采样到Tensorboard",
    "Whether to include sample images in the Tensorboard output.": "是否在Tensorboard输出中包含采样图像",
    "File Format used when saving samples": "保存样本的文件格式",
    "Start sampling automatically after this interval has elapsed.": "经过此间隔后自动开始采样",
    "Add a new sample configuration.": "添加新的采样配置",
    "The number of different image versions to cache if latent caching is enabled.": "启用潜在缓存时缓存的图像版本数",
    "The number of different text versions to cache if latent caching is enabled.": "启用潜在缓存时缓存的文本版本数",
    "Overrides the number of tokens used for captions. If empty, the model default is used, which is 512 on Flux. Comfy samples with 256 tokens though. 77 is the default only for backwards compatibility.": "覆盖标签Token数，留空使用模型默认值",

    # === 训练控制 ===
    "Start Training": "开始训练",
    "Stop Training": "停止训练",
    "Cannot Start Training": "无法开始训练",
    "Training in progress": "训练进行中",
    "Current status": "当前状态",
    "Current status of the training run": "训练运行当前状态",
    "A training is currently running. Stop the training before closing the window.": "训练正在运行中，关闭窗口前请先停止训练",
    "Stopped": "已停止",

    # === 工具 ===
    "Dataset Tool": "数据集工具",
    "Dataset Tools": "数据集工具",
    "Sampling Tool": "采样工具",
    "Convert Model Tools": "模型转换工具",
    "Convert models": "转换模型",
    "Convert": "转换",
    "Profiling Tool": "性能分析工具",
    "Profiling": "性能分析",
    "Start Profiling": "开始分析",
    "End Profiling": "结束分析",
    "Video Tools": "视频工具",
    "Debug": "调试",
    "Debug mode": "调试模式",
    "Save debug information during the training into the debug directory": "训练时将调试信息保存到调试目录",
    "Export Training Config": "导出训练配置",
    "Export the current configuration as a script to run without a UI": "导出当前配置为无UI运行脚本",
    "Open the captioning tool": "打开标签工具",
    "Open the model conversion tool": "打开模型转换工具",
    "Open the model sampling tool": "打开模型采样工具",
    "Open the profiling tools.": "打开性能分析工具",
    "Open the video tools": "打开视频工具",
    "Generate Captions": "生成标签",
    "Generate Masks": "生成遮罩",
    "Batch generate captions": "批量生成标签",
    "Batch generate masks": "批量生成遮罩",
    "Create Captions": "创建标签",
    "Create Masks": "创建遮罩",
    "Replace all captions": "替换所有标签",
    "Replace all masks": "替换所有遮罩",
    "Add as new line": "添加为新行",
    "Add to existing": "添加到现有",
    "Blend with existing": "与现有混合",
    "Subtract from existing": "从现有减去",
    "Initial Caption": "初始标签",
    "Threshold": "阈值",
    "Smooth": "平滑",
    "Remove Borders": "移除边框",
    "Remove black borders from output image": "移除输出图像的黑色边框",
    "Remove black borders from output clip": "移除输出片段的黑色边框",
    "open a dialog to automatically generate captions": "打开自动生成标签对话框",
    "open a dialog to automatically generate masks": "打开自动生成遮罩对话框",
    "open a new directory": "打开新目录",
    "open the current image in Explorer": "在资源管理器中打开当前图像",
    "draw a mask using a brush": "用画笔绘制遮罩",
    "draw a mask using a fill tool": "用填充工具绘制遮罩",
    "Blur Removal": "模糊移除",
    "Draw": "绘制",
    "Fill": "填充",
    "Hex Color": "十六进制颜色",
    "Class Name": "类名",
    "Use Regex": "使用正则",
    "Interpret special tags with regex, such as 'photo.*' to match 'photo, photograph, photon' but not 'telephoto'. Includes exception for '/(' and '/)' syntax found in many booru/e6 tags.": "使用正则匹配特殊标签，如'photo.*'匹配'photo, photograph'",
    "Expand": "展开",
    "Clear": "清除",
    "Open in Explorer": "在资源管理器中打开",
    "Open": "打开",
    "Export": "导出",
    "Generate a zip file with config.json, debug_report.log and settings diff, use this to report bugs or issues": "生成包含配置和调试报告的zip文件，用于报告问题",
    "Select Directory to Save Debug Package": "选择调试包保存目录",
    "Turns on/off Scalene profiling. Only works when OneTrainer is launched with Scalene!": "开关Scalene性能分析，仅在使用Scalene启动时有效",
    "Type of the model": "模型类型",
    "The type of model to convert": "要转换的模型类型",
    "Model Type": "模型类型",
    "Type": "类型",

    # === 云端 ===
    "Enable cloud training": "启用云端训练",
    "Hostname": "主机名",
    "SSH server hostname or IP. Leave empty if you have a Cloud ID or want to automatically create a new cloud.": "SSH服务器主机名或IP，有Cloud ID时留空",
    "Port": "端口",
    "SSH server port. Leave empty if you have a Cloud ID or want to automatically create a new cloud.": "SSH服务器端口，有Cloud ID时留空",
    "User": "用户",
    "SSH keyfile path": "SSH密钥路径",
    "Absolute path to the private key file used for SSH connections. Leave empty to rely on your system SSH configuration.": "SSH私钥文件绝对路径，留空使用系统SSH配置",
    "SSH password": "SSH密码",
    "SSH password for password-based authentication. If you try to use native SCP requires sshpass to be installed. Leave empty to use key-based authentication.": "SSH密码认证，留空使用密钥认证",
    "SSH Public Keys": "SSH公钥",
    "API key": "API密钥",
    "Cloud service API key for RUNPOD. Leave empty for LINUX. This value is stored separately, not saved to your configuration file. ": "RUNPOD云服务API密钥，LINUX留空。单独存储不保存到配置文件",
    "Cloud id": "云ID",
    "Cloud name": "云名称",
    "RUNPOD Cloud ID. The cloud service must have a public IP and SSH service. Leave empty if you want to automatically create a new RUNPOD cloud, or if you're connecting to another cloud provider via SSH Hostname and Port.": "RUNPOD云ID，需要有公网IP和SSH服务",
    "The name of the new cloud instance.": "新云实例名称",
    "Remote Directory": "远程目录",
    "The directory on the cloud where files will be uploaded and downloaded.": "云端上传下载文件的目录",
    "OneTrainer Directory": "OneTrainer目录",
    "The directory for OneTrainer on the cloud.": "云端OneTrainer目录",
    "Volume size": "卷大小",
    "Set the storage volume size in GB. This volume persists only until the cloud is deleted - not a RunPod network volume": "存储卷大小(GB)，云删除后不保留",
    "Min download": "最小下载速度",
    "Set the minimum download speed of the cloud in Mbps.": "云端最小下载速度(Mbps)",
    "File sync method": "文件同步方式",
    "Choose NATIVE_SCP to use scp.exe to transfer files. FABRIC_SFTP uses the Paramiko/Fabric SFTP implementation for file transfers instead.": "NATIVE_SCP使用scp.exe传输，FABRIC_SFTP使用Paramiko SFTP",
    "Install command": "安装命令",
    "The command for installing OneTrainer. Leave the default, unless you want to use a development branch of OneTrainer.": "OneTrainer安装命令，默认即可",
    "Install OneTrainer": "安装OneTrainer",
    "Automatically install OneTrainer from GitHub if the directory doesn't already exist.": "如果目录不存在，自动从GitHub安装OneTrainer",
    "Update OneTrainer": "更新OneTrainer",
    "Update OneTrainer if it already exists on the cloud.": "如果云端已存在则更新OneTrainer",
    "Create cloud via API": "通过API创建云",
    "Create cloud via website": "通过网站创建云",
    "Automatically creates a new cloud instance if both Host:Port and Cloud ID are empty. Currently supported for RUNPOD.": "主机和云ID为空时自动创建云实例，目前支持RUNPOD",
    "Select the GPU type. Enter an API key before pressing the button.": "选择GPU类型，请先输入API密钥",
    "Select the RunPod cloud type. See RunPod's website for details.": "选择RunPod云类型，详见RunPod网站",
    "Reattach id": "重连ID",
    "Reattach now": "立即重连",
    "An id identifying the remotely running trainer. In case you have lost connection or closed OneTrainer, it will try to reattach to this id instead of starting a new remote trainer.": "远程训练器标识ID，断连后可重新连接",
    "Detach remote trainer": "断开远程训练器",
    "Allows the trainer to keep running even if your connection to the cloud is lost.": "允许训练器在断连后继续运行",
    "Delete remote workspace": "删除远程工作空间",
    "Delete the workspace directory on the cloud after training has finished successfully and data has been downloaded.": "训练完成并下载数据后删除云端工作空间目录",
    "Download backups": "下载备份",
    "Download backups from the remote workspace directory to your local machine. It's usually not necessary to download them, because as long as the backups are still available on the cloud, the training can be restarted using one of the cloud's backups.": "从远程下载备份到本地",
    "Download samples": "下载样本",
    "Download samples from the remote workspace directory to your local machine.": "从远程下载样本到本地",
    "Download saved checkpoints": "下载已保存检查点",
    "Download the automatically saved training checkpoints from the remote workspace directory to your local machine.": "从远程下载训练检查点到本地",
    "Download output model": "下载输出模型",
    "Download the final model after training. You can disable this if you plan to use an automatically saved checkpoint instead.": "训练后下载最终模型",
    "Download tensorboard logs": "下载Tensorboard日志",
    "Download Link": "下载链接",
    "Download List": "下载列表",
    "Link List": "链接列表",
    "Single Link": "单个链接",
    "Single Video": "单个视频",
    "Download dataset from Huggingface now, for the purpose of previewing and statistics. Otherwise, it will be downloaded when you start training. Path must be a Huggingface repository.": "从Huggingface下载数据集用于预览和统计",
    "Huggingface models are downloaded to this remote directory.": "Huggingface模型下载到此远程目录",
    "Action on finish": "完成时操作",
    "Action on error": "错误时操作",
    "Action on detached finish": "断连完成时操作",
    "Action on detached error": "断连错误时操作",
    "What to do when training finishes and the data has been fully downloaded: Stop or delete the cloud, or do nothing.": "训练完成且数据下载后的操作",
    "What to do if training stops due to an error: Stop or delete the cloud, or do nothing. Data may be lost.": "训练出错时的操作，数据可能丢失",
    "What to do when training finishes, but the client has been detached and cannot download data. Data may be lost.": "训练完成但客户端已断连时的操作",
    "What to if training stops due to an error, but the client has been detached and cannot download data. Data may be lost.": "训练出错且客户端已断连时的操作",
    "Delete": "删除",
    "Choose LINUX to connect to a linux machine via SSH. Choose RUNPOD for additional functionality such as automatically creating and deleting pods.": "LINUX通过SSH连接Linux机器，RUNPOD自动创建和删除Pod",
    "Create if absent": "不存在则创建",

    # === Tensorboard ===
    "Tensorboard": "Tensorboard",
    "Starts the Tensorboard Web UI during training": "训练时启动Tensorboard Web UI",
    "Tensorboard Port": "Tensorboard端口",
    "Port to use for Tensorboard link": "Tensorboard链接端口",
    "Expose Tensorboard": "暴露Tensorboard",
    "Exposes Tensorboard Web UI to all network interfaces (makes it accessible from the network)": "将Tensorboard暴露到所有网络接口",
    "Tensorboard TCP tunnel": "Tensorboard TCP隧道",
    "Instead of starting tensorboard locally, make a TCP tunnel to a tensorboard on the cloud": "通过TCP隧道连接云端Tensorboard",
    "Always-On Tensorboard": "常驻Tensorboard",
    "Keep Tensorboard accessible even when not training. Useful for monitoring completed training sessions.": "非训练时也保持Tensorboard可访问",

    # === 视频工具 ===
    "Set FPS": "设置FPS",
    "FPS to convert output videos to, set to 0 to keep original rate.": "输出视频帧率，0保持原始",
    "Split at Cuts": "按剪辑分割",
    "Extract Single": "提取单个",
    "Extract Directory": "提取目录",
    "Path to directory with multiple videos to process, including in subdirectories.": "包含子目录的多视频处理目录",
    "Path to folder where downloaded videos will be saved.": "下载视频保存目录",
    "Path to folder where extracted clips will be saved.": "提取片段保存目录",
    "Path to folder where extracted images will be saved.": "提取图像保存目录",
    "Path to txt file with list of links separated by newlines.": "链接列表txt文件路径",
    "Link to single video file to process.": "单个视频文件链接",
    "Link to video/playlist to download. Uses yt-dlp, supports youtube, twitch, instagram, and many other sites.": "视频/播放列表下载链接，支持YouTube等",
    "Maximum length in seconds for saved clips, larger clips will be broken into multiple small clips.": "保存片段最大长度(秒)，超出则分割",

    # === 其他 ===
    "Help": "帮助",
    "Settings": "设置",
    "Temp Device": "临时设备",
    "The device used to temporarily offload models while they are not used. Default:": "模型不使用时的临时卸载设备",
    "Train Device": "训练设备",
    "The device used for training. Can be ": "训练使用的设备",
    "Multi-GPU: Maximum VRAM for ": "多GPU：最大显存 ",
    "The number of learning rate cycles. This is only applicable if the learning rate scheduler supports cycles": "学习率周期数，仅调度器支持时有效",
    "The number of samples used during training. Use repeats to multiply the concept, or samples to specify an exact number of samples used in each epoch.": "训练使用的样本数，用repeats倍乘或samples指定精确数",
    "The number of steps it takes to gradually increase the learning rate from 0 to the specified learning rate. Values >1 are interpeted as a fixed number of steps, values <=1 are intepreted as a percentage of the total training steps (ex. 0.2 = 20% of the total step count)": "学习率从0渐增到指定值的步数，>1为固定步数，<=1为总步数百分比",
    "The number of tags at the start of the caption that are not shuffled or dropped": "标签开头不打乱不丢弃的标签数",
    "The number of frames used for training.": "训练使用的帧数",
    "Unit = float. Method = percentage. For a factor of 0.1, the final LR will be 10% of the initial LR. If the initial LR is 1e-4, the final LR will be 1e-5.": "浮点数，百分比方式。如0.1则最终学习率为初始值的10%",
    "EMA decay must be between 0.5 and 1": "EMA衰减必须在0.5到1之间",
    "Gamma must be between 1 and 20": "Gamma必须在1到20之间",
    "Learning rate min factor must be between 0 and 0.99": "学习率最小因子必须在0到0.99之间",
    "Unmasked probability must be between 0 and 1": "未遮罩概率必须在0到1之间",
    "Unmasked weight must be between 0 and 1": "未遮罩权重必须在0到1之间",
    "Masked prior preservation weight must be between 0 and 1": "遮罩Prior保留权重必须在0到1之间",
    "Aspect Ratio Bucketing": "宽高比分桶",
    "Aspect ratio bucketing enables training on images with different aspect ratios": "宽高比分桶允许在不同宽高比的图像上训练",
    "Image buckets with the least nonzero total images - if 'batch size' is larger than this, these images will be ignored during training! See the wiki for more details.": "非零图像最少的桶，批次大小超过此值时这些图像将被忽略",
    "Select a preset defining which layers to train, or select 'Custom' to define your own.\nA blank 'custom' field or 'Full' will train all layers.": "选择训练层预设，或选'Custom'自定义。空白或'Full'训练所有层",
    "Disables/Enables all visible items in the current view": "禁用/启用当前视图中的所有可见项",
    "Adds a new concept to the current config.": "向当前配置添加新数据集",
    "Adds a new config, which are containers for concepts, which themselves contain your dataset": "添加新配置，配置是数据集的容器",
    "All: All settings, including the samples and concepts are included.": "全部：包含所有设置、采样和数据集",
    "Additional Args": "附加参数",
    "Key name for an argument in your scheduler": "调度器参数键名",
    "Value for an argument in your scheduler. Some special values can be used, wrapped in percent signs: LR, EPOCHS, STEPS_PER_EPOCH, TOTAL_STEPS, SCHEDULER_STEPS. Note that OneTrainer calls step() after every individual learning step, not every epoch, so what Torch calls 'epoch' you should treat as 'step'.": "调度器参数值，可用特殊值：LR, EPOCHS, TOTAL_STEPS等",
    "Learning Rate Scheduler Settings": "学习率调度器设置",
    "Selects the type of learning rate scaling to use during training. Functionally equated as: LR * SQRT(selection)": "学习率缩放类型，等效于: LR * SQRT(选择值)",
    "Python class module and name for the custom scheduler class, in the form of <module>.<class_name>.": "自定义调度器类，格式：<模块>.<类名>",
    "Configure the auxiliary AdamW_adv optimizer": "配置辅助AdamW_adv优化器",
    "Method used to drop captions. 'Full' will drop the entire caption past the 'kept' tags with a certain probability, 'Random' will drop individual tags with the set probability, and 'Random Weighted' will linearly increase the probability of dropping tags, more likely to preseve tags near the front with full probability to drop at the end.": "标签丢弃方式：Full整体丢弃，Random随机丢弃，Random Weighted加权丢弃",
    "List of tags which will be whitelisted/blacklisted by dropout. 'Whitelist' tags will never be dropped but all others may be, 'Blacklist' tags may be dropped but all others will never be, 'None' may drop any tags. Can specify either a delimiter-separated list in the field, or a file path to a .txt or .csv file with entries separated by newlines.": "丢弃白/黑名单标签列表，可输入分隔列表或文件路径",
    "Comma-separated list of types of capitalization randomization to perform. 'capslock' for ALL CAPS, 'title' for First Letter Of Every Word, 'first' for First word only, 'random' for rAndOMiZeD lEtTERs.": "大小写随机化类型：capslock全大写，title首字母大写，first首词大写，random随机",
    "If enabled, layer filter patterns are interpreted as regular expressions. Otherwise, simple substring matching is used.": "启用后层过滤器使用正则匹配，否则使用子串匹配",
    "The source for prompts used during training. When selecting ": "训练提示词来源。选择",
    "STANDARD: Standard finetuning with the sample as training target\n": "标准：以样本为训练目标的标准微调\n",
    "VALIDATION: Use concept for validation instead of training\n": "验证：用数据集进行验证而非训练\n",
    "WEIGHT_DTYPE: Reduce gradients between GPUs in your weight data type; can be imprecise, but more efficient than float32\n": "WEIGHT_DTYPE：以权重数据类型归约梯度，可能比float32不精确但更高效\n",
    "Directory or Hugging Face repository of a VAE model in diffusers format. Can be used to override the VAE included in the base model. Using a safetensor VAE file will cause an error that the model cannot be loaded.": "diffusers格式的VAE模型目录或Hugging Face仓库，用于覆盖基础模型的VAE",
    "Can be used to override the transformer in the base model. Safetensors and GGUF files are supported, local and on Huggingface. If a GGUF file is used, the DataType must also be set to GGUF": "覆盖基础模型的Transformer，支持safetensors和GGUF",
    "Filename, directory or Hugging Face repository of the base model this LoRA/embedding was trained on": "此LoRA/嵌入训练的基础模型",
    "Filename, directory or Hugging Face repository of the decoder model": "解码器模型路径",
    "Filename, directory or Hugging Face repository of the effnet encoder model": "Effnet编码器模型路径",
    "Filename, directory or Hugging Face repository of the prior model": "Prior模型路径",
    "Filename, directory or Hugging Face repository of the text encoder 4 model": "文本编码器4模型路径",
    "Decoder Data Type": "解码器数据类型",
    "The decoder weight data type": "解码器权重数据类型",
    "Decoder Text Encoder Data Type": "解码器文本编码器数据类型",
    "The decoder text encoder weight data type": "解码器文本编码器权重数据类型",
    "Decoder VQGAN Data Type": "解码器VQGAN数据类型",
    "The decoder vqgan weight data type": "解码器VQGAN权重数据类型",
    "Decoder Model": "解码器模型",
    "Effnet Encoder Data Type": "Effnet编码器数据类型",
    "The effnet encoder weight data type": "Effnet编码器权重数据类型",
    "Effnet Encoder Model": "Effnet编码器模型",
    "Prior Model": "Prior模型",
    "The Embedding weight data type used for training. This can reduce memory consumption, but reduces precision": "嵌入权重数据类型，可减少内存但降低精度",
    "Embedding Weight Data Type": "嵌入权重数据类型",
    "The type of low-parameter finetuning method.": "低参数微调方法类型",
    "The text encoder 1 weight data type": "文本编码器1权重数据类型",
    "The text encoder 2 weight data type": "文本编码器2权重数据类型",
    "The text encoder 3 weight data type": "文本编码器3权重数据类型",
    "The text encoder 4 weight data type": "文本编码器4权重数据类型",
    "Loading model ": "加载模型 ",
    "Saving model ": "保存模型 ",
    "Model converted": "模型已转换",
    "Release all models from VRAM": "从显存释放所有模型",
    "Show Augmentations": "显示增强",
    "Show Disabled": "显示禁用项",
    "Skip First": "跳过首个",
    "Folder": "文件夹",
    "Secure": "安全",
    "Inactive": "未激活",
    "Enable": "启用",
    "Disable": "禁用",
    "Community": "社区",
    "Standard": "标准",
    "Square": "方形",
    "Wide": "宽图",
    "Tall": "长图",
    "Average length of caption in concept by character count. For token count, assume ~2 tokens/word": "标签平均长度（字符数），Token数约2/词",
    "Largest caption in concept by character count. For token count, assume ~2 tokens/word": "最长标签（字符数），Token数约2/词",
    "Smallest caption in concept by character count. For token count, assume ~2 tokens/word": "最短标签（字符数），Token数约2/词",
    "Average size of images in the concept by number of pixels (width * height)": "图像平均尺寸（宽x高像素）",
    "Largest image in the concept by number of pixels (width * height)": "最大图像尺寸（宽x高像素）",
    "Smallest image in the concept by number of pixels (width * height)": "最小图像尺寸（宽x高像素）",
    "Average length of videos in the concept by number of frames": "视频平均帧数",
    "Total number of caption files which lack a corresponding image file - if >0, check your data set! If using 'from file name' or 'from single text file' then this can be ignored.": "缺少对应图像的标签文件数，>0请检查数据集",
    "Total number of caption files, any .txt file. With advanced scan, includes the total number of captions on separate lines across all files in parentheses.": "标签文件总数（.txt文件）",
    "Total number of directories including and under (if 'include subdirectories' is enabled) the main concept directory": "数据集目录及子目录总数",
    "Total number of image files, any of the extensions ": "图像文件总数，扩展名：",
    "Total number of mask files which lack a corresponding image file - if >0, check your data set!": "缺少对应图像的遮罩文件数，>0请检查数据集",
    "Total number of mask files, any file ending in '-masklabel.png'": "遮罩文件总数（-masklabel.png结尾）",
    "Total number of video files with an associated caption": "有关联标签的视频文件总数",
    "Total number of video files, any of the extensions ": "视频文件总数，扩展名：",
    "Number of tokens for captions": "标签Token数",
    "The number of different image versions to cache if latent caching is enabled.": "潜在缓存的图像版本数",
    "The number of different text versions to cache if latent caching is enabled.": "潜在缓存的文本版本数",
    "Start saving automatically after this interval has elapsed.": "经过此间隔后自动开始保存",
    "Download TensorBoard event logs from the remote workspace directory to your local machine. They can then be viewed locally in TensorBoard. It is recommended to disable \\": "从远程下载Tensorboard日志到本地查看",
    "Multi-GPU: A comma-separated list of device indexes. If empty, all your GPUs are used. With a list such as \\": "多GPU：逗号分隔的设备索引列表，留空使用所有GPU",
}
