name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: actual-behavior
    attributes:
      label: What happened?
      description: Give a description of what happened?
      placeholder: Tell us what you saw!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect would happen?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you saw!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Generate and upload debug_report.log
      description: Please attach your `debug_report.log` file. This file is generated by double-clicking on `export_debug.bat` in the OneTrainer folder on Windows, or by running `./run-cmd.sh generate_debug_report` on Mac/Linux.
      placeholder: Drag and drop the file or click the paperclip icon below to upload.
      render: ''
