name: Check Lockfile
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Check-Lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
      - name: Check lockfile
        run: |
          pixi lock --check
