def create_new_concept() -> dict:
    return {
        "name": "",
        "path": "",
        "prompt_source": "sample",
        "prompt_path": "",
        "enable_crop_jitter": True,
        "enable_random_flip": True,
        "enable_random_rotate": False,
        "random_rotate_max_angle": 0.0,
        "enable_random_brightness": False,
        "random_brightness_max_strength": 0.0,
        "enable_random_contrast": False,
        "random_contrast_max_strength": 0.0,
        "enable_random_saturation": False,
        "random_saturation_max_strength": 0.0,
        "enable_random_hue": False,
        "random_hue_max_strength": 0.0,
        "include_subdirectories": False,
    }
