from modules.model.StableDiffusionXLModel import StableDiffusionXLModel
from modules.modelSaver.GenericEmbeddingModelSaver import make_embedding_model_saver
from modules.modelSaver.stableDiffusionXL.StableDiffusionXLEmbeddingSaver import StableDiffusionXLEmbeddingSaver

StableDiffusionXLEmbeddingModelSaver = make_embedding_model_saver(
    model_class=StableDiffusionXLModel,
    embedding_saver_class=StableDiffusionXLEmbeddingSaver,
)
