from modules.model.StableDiffusionModel import StableDiffusionModel
from modules.modelSaver.GenericFineTuneModelSaver import make_fine_tune_model_saver
from modules.modelSaver.stableDiffusion.StableDiffusionEmbeddingSaver import StableDiffusionEmbeddingSaver
from modules.modelSaver.stableDiffusion.StableDiffusionModelSaver import StableDiffusionModelSaver

StableDiffusionFineTuneModelSaver = make_fine_tune_model_saver(
    model_class=StableDiffusionModel,
    model_saver_class=StableDiffusionModelSaver,
    embedding_saver_class=StableDiffusionEmbeddingSaver,
)
