from modules.model.StableDiffusionModel import StableDiffusionModel
from modules.modelSaver.GenericEmbeddingModelSaver import make_embedding_model_saver
from modules.modelSaver.stableDiffusion.StableDiffusionEmbeddingSaver import StableDiffusionEmbeddingSaver

StableDiffusionEmbeddingModelSaver = make_embedding_model_saver(
    model_class=StableDiffusionModel,
    embedding_saver_class=StableDiffusionEmbeddingSaver,
)
