from modules.model.StableDiffusionXLModel import StableDiffusionXLModel
from modules.modelSaver.GenericFineTuneModelSaver import make_fine_tune_model_saver
from modules.modelSaver.stableDiffusionXL.StableDiffusionXLEmbeddingSaver import StableDiffusionXLEmbeddingSaver
from modules.modelSaver.stableDiffusionXL.StableDiffusionXLModelSaver import StableDiffusionXLModelSaver

StableDiffusionXLFineTuneModelSaver = make_fine_tune_model_saver(
    model_class=StableDiffusionXLModel,
    model_saver_class=StableDiffusionXLModelSaver,
    embedding_saver_class=StableDiffusionXLEmbeddingSaver,
)
