from modules.model.StableDiffusion3Model import StableDiffusion3Model
from modules.modelSaver.GenericEmbeddingModelSaver import make_embedding_model_saver
from modules.modelSaver.stableDiffusion3.StableDiffusion3EmbeddingSaver import StableDiffusion3EmbeddingSaver

StableDiffusion3EmbeddingModelSaver = make_embedding_model_saver(
    model_class=StableDiffusion3Model,
    embedding_saver_class=StableDiffusion3EmbeddingSaver,
)
